<?php

namespace CarsBundle\Repository;

/**
 * PartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPartsByCar($id)
    {
        return $this->createQueryBuilder('p')
            ->where(':car_id MEMBER OF p.cars')
            ->setParameter('car_id', $id)
            ->getQuery()->getResult();
    }
}
