<?php

namespace CarsBundle\Repository;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSuppliers($isImporter)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT s,COUNT(p.id) AS count_parts
                FROM CarsBundle:Supplier s
                LEFT JOIN s.parts p 
                WHERE s.isImporter = :isImporter
                GROUP BY p.supplier'
        );

        $query->setParameter('isImporter', $isImporter);

        return $query->getResult();
    }
}
